#!/usr/bin/env python3
from __future__ import annotations

import json
import re
from datetime import datetime
from pathlib import Path

ROOT = Path('/Users/beemo/bmo_hermes_dashboard')
SOURCE_DIR = Path('/Users/beemo/.hermes/cron/output/6aecae3e2df5')
OUT = ROOT / 'data' / 'daily_fortunes.json'


def extract_response(text: str) -> str:
    marker = '\n## Response\n'
    if marker in text:
        return text.split(marker, 1)[1].strip()
    # Defensive fallback: never expose the prompt if the expected marker is absent.
    return ''


def parse_date_from_filename(path: Path) -> str:
    m = re.match(r'(\d{4}-\d{2}-\d{2})_', path.name)
    return m.group(1) if m else ''


def title_from_date(iso_date: str) -> str:
    if not iso_date:
        return '운세 기록'
    dt = datetime.strptime(iso_date, '%Y-%m-%d')
    weekdays = '월화수목금토일'
    return f'{dt.year}년 {dt.month}월 {dt.day}일 {weekdays[dt.weekday()]}요일 운세'


def sanitize(text: str) -> str:
    if not text:
        return ''

    replacements = [
        # Remove likely name/Hanja identity lines generated by the fortune job.
        (r'^[가-힣]{2,4}\s*\([一-龥]+\)\s*님\s*기준\s*[·ㆍ-]?\s*', '대상자 비공개 기준 · ', re.MULTILINE),
        (r'^[가-힣]{2,4}\s*님\s*기준\s*[·ㆍ-]?\s*', '대상자 비공개 기준 · ', re.MULTILINE),
        (r'^대상\s*:\s*[가-힣]{2,4}\s*/\s*[一-龥]{2,10}\s*(주인님|님)?\s*$', '대상: 비공개', re.MULTILINE),
        (r'^대상\s*:\s*[가-힣]{2,4}\s*(주인님|님)?\s*$', '대상: 비공개', re.MULTILINE),
        (r'^(\*\*대상:\*\*)\s*[가-힣]{2,4}\s*\([^)]+\)\s*(주인님|님)?\s*$', r'\1 비공개', re.MULTILINE),
        (r'^(\*\*대상:\*\*)\s*[가-힣]{2,4}\s*(주인님|님)?\s*$', r'\1 비공개', re.MULTILINE),

        (r'\b(19|20)\d{2}[./-]?\d{1,2}[./-]?\d{1,2}\b', '[생년월일 비공개]', 0),
        # Mask Korean location phrases down to city/district granularity.
        (r'(서울|부산|대구|인천|광주|대전|울산|세종|경기|강원|충북|충남|전북|전남|경북|경남|제주)\s*[가-힣]{1,12}(구|군|시)', '[주소 비공개]', 0),
        # Remove Hanja parenthetical identity remnants.
        (r'\([一-龥]{2,10}\)', '(한자 비공개)', 0),
    ]
    for pattern, repl, flags in replacements:
        text = re.sub(pattern, repl, text, flags=flags)

    # If the model repeats a direct identity prefix in headings, neutralize it.
    text = re.sub(r'##\s*완료\s*—\s*(.+?)오늘의 운세\s*$', r'## 완료 — \1오늘의 운세', text, flags=re.MULTILINE)
    return text.strip()


def build() -> dict:
    entries = []
    for path in sorted(SOURCE_DIR.glob('*.md'), reverse=True):
        raw = path.read_text(encoding='utf-8', errors='replace')
        response = sanitize(extract_response(raw))
        if not response or response == '[SILENT]':
            continue
        iso_date = parse_date_from_filename(path)
        entries.append({
            'date': iso_date,
            'title': title_from_date(iso_date),
            'source': 'daily-fortune',
            'privacy': 'name_birthdate_address_hidden',
            'content': response,
        })
    checked_at = datetime.now().astimezone().strftime('%Y-%m-%d %H:%M:%S %Z')
    return {
        'updatedAt': checked_at,
        'count': len(entries),
        'privacyNote': '이름, 생년월일, 출생지, 거주지 등 개인 식별 정보는 공개 데이터에서 제외하거나 마스킹했습니다.',
        'entries': entries,
    }


def main() -> None:
    OUT.parent.mkdir(parents=True, exist_ok=True)
    data = build()
    OUT.write_text(json.dumps(data, ensure_ascii=False, indent=2) + '\n', encoding='utf-8')


if __name__ == '__main__':
    main()
